### ISSUE TITLE
Bug when running ASF .NET 9.0 upgrade

### ISSUE THREAD

**Issue by EsdrubalMagano** [maxisoft/ASFFreeGames#110]
Hey there!

Here is a bug that occurs when running ASF with the ASFFreeGames plugin. Probably related to the ASF upgrade to .NET 9.0. Work's fine without the ASFFreeGames plugin

2024-12-01 22:41:28|ArchiSteamFarm-5979|INFO|ASF|InitCore() ArchiSteamFarm V6.1.0.1 (linux-arm64/1389e4e4c2304043b8fa73924b8db4e4 | .NET 9.0.0; linux-arm64; Ubuntu 22.04.5 LTS) in [/home/ubuntu/ASF]
2024-12-01 22:41:28|ArchiSteamFarm-5979|INFO|ASF|InitCore() Copyright © 2015-2024 JustArchiNET
2024-12-01 22:41:28|ArchiSteamFarm-5979|INFO|ASF|InitPlugins() Initializing Plugins...
2024-12-01 22:41:29|ArchiSteamFarm-5979|ERROR|ASF|InitPlugins() Failed due to error: System.Threading.AsyncLocal`1
2024-12-01 22:41:29|ArchiSteamFarm-5979|ERROR|ASF|InitPlugins() System.TypeLoadException: Could not load type 'System.Threading.AsyncLocal`1' from assembly 'System.Threading, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Maxisoft.ASF.ASFFreeGamesPlugin..ctor()
   at lambda_method1(Closure, LifetimeContext, CompositionOperation)
   at System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.<>c__DisplayClass3_2`1.<GetImportManyDescriptor>b__4(ExportDescriptor e)
   at System.Linq.Enumerable.ArraySelectIterator`2.Fill(ReadOnlySpan`1, Span`1, Func`2)
   at System.Linq.Enumerable.ArraySelectIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1)
   at System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.<>c__DisplayClass3_1`1.<GetImportManyDescriptor>b__3(LifetimeContext c, CompositionOperation o)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.Hosting.CompositionHost.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.CompositionContext.GetExport(CompositionContract)
   at System.Composition.CompositionContext.GetExports(Type, String)
   at System.Composition.CompositionContext.GetExports[TExport](String)
   at System.Composition.CompositionContext.GetExports[TExport]()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
2024-12-01 22:41:39|ArchiSteamFarm-5979|ERROR|ASF|Exit() Exiting with 1 error code!

- OS: Ubuntu 22.04
- ASF: 6.1.0.1
- Plugin: v1.8.0

**Comment by JerryWn12** [comment]
Same here
