### ISSUE TITLE
Unable to load previous completed app dict - Exiting with nonzero error code

### ISSUE THREAD

**Issue by Retardium** [maxisoft/ASFFreeGames#2]
**Describe the bug**
While ASF tries to load the plugin it gets a "unable to load previous completed app dict" error and exits with nonzero error code.
Without the plugin ASF works fine and there are no errors.

**To Reproduce**
It's probably hard to reproduce, since I don't understand the cause and can't explain how to. Sorry.
I use your plugin for months now without issues and changed nothing on system except for regular updates.

**Log ASF**
```diff 2022-06-09 13:32:55|ArchiSteamFarm-12082|INFO|ASF|InitCore() ArchiSteamFarm V5.2.7.1 (linux-x64/c2836126-a1c9-4ecf-9d5b-40e4ffd756c5 | .NET 6.0.5; debian.11-x64; Linux 4.9.0-18-amd64 #1 SMP Debian 4.9.303-1 (2022-03-07))
2022-06-09 13:32:56|ArchiSteamFarm-12082|INFO|ASF|InitCore() Copyright © 2015-2022 JustArchiNET
2022-06-09 13:32:56|ArchiSteamFarm-12082|INFO|ASF|InitPlugins() Initializing Plugins...
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|InitPlugins() Loading ASFEnhance V1.6.4.469...
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|OnLoaded() 
==========================================
 █████╗ ███████╗███████╗███████╗███╗   ██╗██╗  ██╗ █████╗ ███╗   ██╗ ██████╗███████╗
██╔══██╗██╔════╝██╔════╝██╔════╝████╗  ██║██║  ██║██╔══██╗████╗  ██║██╔════╝██╔════╝
███████║███████╗█████╗  █████╗  ██╔██╗ ██║███████║███████║██╔██╗ ██║██║     █████╗  
██╔══██║╚════██║██╔══╝  ██╔══╝  ██║╚██╗██║██╔══██║██╔══██║██║╚██╗██║██║     ██╔══╝  
██║  ██║███████║██║     ███████╗██║ ╚████║██║  ██║██║  ██║██║ ╚████║╚██████╗███████╗
╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝╚══════╝
ASFEnhance Version 1.6.4.469
Developed by Chr_, email chr@chrxw.com
https://afdian.net/@chr233
==========================================
Use Command "ASFEVERSION" / "AV" to check the plugin's latest version
Use Command "ASFEUPDATE" / "AU" to update the plugin
==========================================

2022-06-09 13:32:55|ArchiSteamFarm-12082|INFO|ASF|InitPlugins() ASFEnhance has been loaded successfully!
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|InitPlugins() Loading SteamTokenDumperPlugin V5.2.7.1...
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|InitPlugins() SteamTokenDumperPlugin has been loaded successfully!
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|InitPlugins() Loading CaseInsensitiveASF V0.4.1.0...
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|OnLoaded() Case Insensitive ASF Plugin by Ryzhehvost, powered by ginger cats
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|InitPlugins() CaseInsensitiveASF has been loaded successfully!
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|InitPlugins() Loading ASFFreeGamesPlugin V1.2.1.0...
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|InitPlugins() ASFFreeGamesPlugin has been loaded successfully!
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|InitPlugins() You've loaded one or multiple custom plugins into ASF. Since we're unable to offer support for modded setups, please contact the appropriate developers of the plugins that you decided to use in case of any issues.
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|UpdateAndRestart() ASF will automatically check for new versions every 12 hours.
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|Update() Checking for new version...
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|Update() Local version: 5.2.7.1 | Remote version: 5.2.7.1
2022-06-09 13:32:57|ArchiSteamFarm-12082|INFO|ASF|OnASFInit() SteamTokenDumperPlugin is currently disabled according to your configuration. If you'd like to help SteamDB in data submission, please check out our wiki.
2022-06-09 13:32:57|ArchiSteamFarm-12082|WARN|ASF|RegisterBots() You're running more personal bot accounts than our upper recommended limit (10). Be advised that this setup is not supported and might cause various Steam-related issues, including account suspensions. Check out the FAQ for more details.
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot1|Start() Starting...
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot1|Connect() Connecting...
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot10|Start() Starting...
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot2|Start() Starting...
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot5|Start() Starting...
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot2|Start() Starting...
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot7|Start() Starting...
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot9|Start() Starting...
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot15|Start() Starting...
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot12|Start() Starting...
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot11|Start() Starting...
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot13|Start() Starting...
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot3|Start() Starting...
2022-06-09 13:33:08|ArchiSteamFarm-12082|INFO|bot6|Start() Starting...
2022-06-09 13:33:09|ArchiSteamFarm-12082|INFO|bot8|Start() Starting...
2022-06-09 13:33:09|ArchiSteamFarm-12082|INFO|bot14|Start() Starting...
2022-06-09 13:33:09|ArchiSteamFarm-12082|INFO|bot1|OnConnected() Connected to Steam!
2022-06-09 13:33:09|ArchiSteamFarm-12082|INFO|bot1|OnConnected() Logging in...
2022-06-09 13:33:09|ArchiSteamFarm-12082|INFO|bot1|OnLoggedOn() Successfully logged on as *****************/bot1.
2022-06-09 13:33:10|ArchiSteamFarm-12082|INFO|bot1|Init() Logging in to ISteamUserAuth...
2022-06-09 13:33:10|ArchiSteamFarm-12082|INFO|bot1|Init() Success!
!2022-06-09 13:33:10|ArchiSteamFarm-12082|ERROR|ASF|LoadFromFile() Unable to load previous completed app dict
2022-06-09 13:33:11|ArchiSteamFarm-12082|INFO|bot1|IsAnythingToFarm() Checking first badge page...
2022-06-09 13:33:11|ArchiSteamFarm-12082|INFO|bot1|StartFarming() We don't have anything to farm on this account!
2022-06-09 13:33:18|ArchiSteamFarm-12082|INFO|bot10|Connect() Connecting...
2022-06-09 13:33:18|ArchiSteamFarm-12082|INFO|bot10|OnConnected() Connected to Steam!
2022-06-09 13:33:18|ArchiSteamFarm-12082|INFO|bot10|OnConnected() Logging in...
2022-06-09 13:33:19|ArchiSteamFarm-12082|INFO|bot10|OnLoggedOn() Successfully logged on as *****************/smurfgeneratorcom.
2022-06-09 13:33:19|ArchiSteamFarm-12082|INFO|bot10|Init() Logging in to ISteamUserAuth...
2022-06-09 13:33:19|ArchiSteamFarm-12082|INFO|bot10|IsAnythingToFarm() Checking first badge page...
2022-06-09 13:33:19|ArchiSteamFarm-12082|INFO|bot10|Init() Success!
! 2022-06-09 13:33:19|ArchiSteamFarm-12082|ERROR|ASF|LoadFromFile() Unable to load previous completed app dict
2022-06-09 13:33:20|ArchiSteamFarm-12082|INFO|bot10|StartFarming() We don't have anything to farm on this account!
2022-06-09 13:33:28|ArchiSteamFarm-12082|INFO|bot2|Connect() Connecting...
2022-06-09 13:33:28|ArchiSteamFarm-12082|INFO|bot2|OnConnected() Connected to Steam!
2022-06-09 13:33:28|ArchiSteamFarm-12082|INFO|bot2|OnConnected() Logging in...
2022-06-09 13:33:29|ArchiSteamFarm-12082|INFO|bot2|OnLoggedOn() Successfully logged on as *****************/bot2.
2022-06-09 13:33:29|ArchiSteamFarm-12082|INFO|bot2|Init() Logging in to ISteamUserAuth...
2022-06-09 13:33:29|ArchiSteamFarm-12082|INFO|bot2|IsAnythingToFarm() Checking first badge page...
2022-06-09 13:33:30|ArchiSteamFarm-12082|INFO|bot2|Init() Success!
!2022-06-09 13:33:30|ArchiSteamFarm-12082|ERROR|ASF|LoadFromFile() Unable to load previous completed app dict
2022-06-09 13:33:31|ArchiSteamFarm-12082|INFO|bot2|IsAnythingToFarm() Checking other badge pages...
2022-06-09 13:33:33|ArchiSteamFarm-12082|INFO|bot2|Farm() We have a total of 6 games (21 cards) left to farm (~10 hours, 30 minutes remaining)...
2022-06-09 13:33:33|ArchiSteamFarm-12082|INFO|bot2|Farm() Chosen farming algorithm: Simple
2022-06-09 13:33:33|ArchiSteamFarm-12082|INFO|bot2|IsPlayableGame() Farming 960990 (Beyond: Two Souls) is temporarily disabled, as ASF is not able to play that game at the moment.
2022-06-09 13:33:33|ArchiSteamFarm-12082|INFO|bot2|IsPlayableGame() Farming 1283190 (Neighbours back From Hell) is temporarily disabled, as ASF is not able to play that game at the moment.
2022-06-09 13:33:33|ArchiSteamFarm-12082|INFO|bot2|IsPlayableGame() Farming 537800 (Bomber Crew) is temporarily disabled, as ASF is not able to play that game at the moment.
2022-06-09 13:33:33|ArchiSteamFarm-12082|INFO|bot2|IsPlayableGame() Farming 527230 (For The King) is temporarily disabled, as ASF is not able to play that game at the moment.
2022-06-09 13:33:33|ArchiSteamFarm-12082|INFO|bot2|IsPlayableGame() Farming 555510 (MachiaVillain) is temporarily disabled, as ASF is not able to play that game at the moment.
2022-06-09 13:33:33|ArchiSteamFarm-12082|INFO|bot2|IsPlayableGame() Farming 675010 (MudRunner) is temporarily disabled, as ASF is not able to play that game at the moment.
2022-06-09 13:33:33|ArchiSteamFarm-12082|INFO|bot2|IsAnythingToFarm() Checking first badge page...
2022-06-09 13:33:34|ArchiSteamFarm-12082|INFO|bot2|IsAnythingToFarm() Checking other badge pages...
2022-06-09 13:33:35|ArchiSteamFarm-12082|INFO|bot2|Farm() Farming finished!
2022-06-09 13:33:38|ArchiSteamFarm-12082|INFO|bot5|Connect() Connecting...
2022-06-09 13:33:38|ArchiSteamFarm-12082|INFO|bot5|OnConnected() Connected to Steam!
2022-06-09 13:33:38|ArchiSteamFarm-12082|INFO|bot5|OnConnected() Logging in...
2022-06-09 13:33:39|ArchiSteamFarm-12082|INFO|bot5|OnLoggedOn() Successfully logged on as *****************/bot5.
2022-06-09 13:33:39|ArchiSteamFarm-12082|WARN|bot5|OnLoggedOn() This account is limited, farming process is unavailable until the restriction is removed!
2022-06-09 13:33:39|ArchiSteamFarm-12082|INFO|bot5|Init() Logging in to ISteamUserAuth...
2022-06-09 13:33:39|ArchiSteamFarm-12082|INFO|bot5|StartFarming() We don't have anything to farm on this account!
2022-06-09 13:33:39|ArchiSteamFarm-12082|INFO|bot5|Init() Success!
!2022-06-09 13:33:39|ArchiSteamFarm-12082|ERROR|ASF|LoadFromFile() Unable to load previous completed app dict
-2022-06-09 13:33:40|ArchiSteamFarm-12082|FATAL|ASF|OnUnhandledException() System.MissingMethodException: Method not found: 'UInt32 ArchiSteamFarm.Core.Utilities.GetUnixTime()'.
-   at Maxisoft.ASF.ASFFreeGamesPlugin.CollectGames(IEnumerable`1 bots, CancellationToken cancellationToken)
-   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& )
-   at Maxisoft.ASF.ASFFreeGamesPlugin.CollectGames(IEnumerable`1 bots, CancellationToken cancellationToken)
-   at Maxisoft.ASF.ASFFreeGamesPlugin.CollectGamesOnClock(Object source)
-   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object )
-   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
-   at System.Threading.ThreadPoolWorkQueue.Dispatch()
-   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
-  at System.Threading.Thread.StartCallback()
-2022-06-09 13:33:40|ArchiSteamFarm-12082|ERROR|ASF|Exit() Exiting with nonzero error code!
2022-06-09 13:33:40|ArchiSteamFarm-12082|INFO|bot8|Stop() Stopping...
2022-06-09 13:33:40|ArchiSteamFarm-12082|INFO|bot1|Stop() Stopping...
2022-06-09 13:33:40|ArchiSteamFarm-12082|INFO|bot9|Stop() Stopping...
2022-06-09 13:33:40|ArchiSteamFarm-12082|INFO|bot7|Stop() Stopping...
2022-06-09 13:33:40|ArchiSteamFarm-12082|INFO|bot6|Stop() Stopping...
2022-06-09 13:33:40|ArchiSteamFarm-12082|INFO|bot2|Stop() Stopping...
2022-06-09 13:33:40|ArchiSteamFarm-12082|INFO|bot4|Stop() Stopping...
2022-06-09 13:33:40|ArchiSteamFarm-12082|INFO|bot3|Stop() Stopping...
2022-06-09 13:33:40|ArchiSteamFarm-12082|INFO|bot5|Stop() Stopping...
```

**Expected behavior**
ASF loads the plugin without errors, like it worked before for months.

**Server (please complete the following information):**
 - OS: Debian Bullseye
 - Version: Everything UP2D including ASF (V5.2.7.1)

**Additional context**
Other installed plugins: ASFEnhance, Case-Insensitive-ASF

**Comment by woctezuma** [comment]
This is the error:

```
System.MissingMethodException: Method not found: 'UInt32 ArchiSteamFarm.Core.Utilities.GetUnixTime()
```

**Comment by Retardium** [comment]
Both errors only appear when the plugin is installed.
Without ASFFreeGames my ASF installation is working fine.

I can't tell if these errors appear due to misconfiguration, a bug in the code of ASF, the plugin or dependencies, tho.

**Comment by woctezuma** [comment]
It is possible that the plugin needs to be updated if ASF has deprecated some functions or changed some function signatures.

**Comment by maxisoft** [comment]
I'm working on this issue thank for the report

**Comment by maxisoft** [comment]
Bug cause is a `ArchiSteamFarm.Core.Utilities.GetUnixTime()` [call](https://github.com/maxisoft/ASFFreeGames/blob/03fa8338762891b9c7d59c8c1ce2009f3698f79b/ASFFreeGames/ASFFreeGamesPlugin.cs#L209=) which got somehow trimed out of asf binary.
This lead to a `System.MissingMethodException` and asf is crashing

So I added a workaround and I'll publish a Release later today.

https://github.com/maxisoft/ASFFreeGames/blob/a6fb2ceb35505c6f996bede9bd6cbc6cffb04646/ASFFreeGames/ASFFreeGamesPlugin.cs#L209

**Comment by maxisoft** [comment]
New pre-release with this issue fixed is here https://github.com/maxisoft/ASFFreeGames/releases/tag/v1.2.2

**Comment by maxisoft** [comment]
Closing as this issue seems resolved with latest plugin release.
If not feel free to reopen this issue.

**Comment by VladozPlay** [comment]
![image](https://github.com/maxisoft/ASFFreeGames/assets/18194595/dfecb9a6-38bf-4d72-af58-f3b1169a2098)
error
