### ISSUE TITLE
ASF issues an error on the latest version

### ISSUE THREAD

**Issue by lzrdblzzrd** [maxisoft/ASFFreeGames#50]
```
2023-12-16 14:46:17|ArchiSteamFarm-18|ERROR|ASF|OnBotLoggedOn() System.MissingMethodException: Method not found: 'UInt32 System.BitConverter.ToUInt32(System.ReadOnlySpan`1<Byte>)'.
   at Maxisoft.ASF.RandomUtils.GaussianRandom.NextDouble()
   at Maxisoft.ASF.RandomUtils.GaussianRandom.NextGaussian(Double mean, Double standardDeviation)
   at Maxisoft.ASF.CollectIntervalManager.GetRandomizedTimerDelay(Double meanSeconds, Double stdSeconds, Double minSeconds, Double maxSeconds)
   at Maxisoft.ASF.CollectIntervalManager.StartTimerIfNeeded()
   at Maxisoft.ASF.ASFFreeGamesPlugin.StartTimerIfNeeded()
   at Maxisoft.ASF.ASFFreeGamesPlugin.RegisterBot(Bot bot)
   at Maxisoft.ASF.ASFFreeGamesPlugin.OnBotLoggedOn(Bot bot)
   at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnBotLoggedOn(Bot bot)
```

ASF version: 5.5.0.10 (Docker)
ASFFreeGames version: 1.4.1 (Pre-release)

This error is not critical, since after this error (the error occurs for each running bot, not once) ASF continues to work, but the plugin itself does not work.

**Comment by azhuge233** [comment]
Same on ASF 5.5.0.11
![Snipaste_2023-12-20_13-19-51](https://github.com/maxisoft/ASFFreeGames/assets/17763056/0ab9b979-38cf-47ed-8954-4cd04d81c959)
![Snipaste_2023-12-20_13-14-42](https://github.com/maxisoft/ASFFreeGames/assets/17763056/5148a931-f007-41a5-9335-7a2cde461b66)

**Comment by TheSparkyGhost** [comment]
**The errors I get ARE fatal, causing ASF to immediately shutdown.**
-
 **Here are the errors I get when ArchiSteamFarm is first loaded using ASFreeGames.**
------------------------------------
![asffarmerror00](https://github.com/maxisoft/ASFFreeGames/assets/135796876/f9ecac14-f2a8-4dbb-ac2b-90a9f2030030)

**This is the error it gives just before ArchiSteamFarm immediately closes itself.**
------------------------------------
![asffarmerror01](https://github.com/maxisoft/ASFFreeGames/assets/135796876/a9041132-2e2f-473a-8e7c-d73dee1a6eb8)

**I have two bots loaded.. this worked until about a week ago, the program now closes just as soon as it searches for free games. I'm on Windows 11, using ASF V5.5.0.11, and ASFFreeGames V1.3.0.0.**
-

**Comment by lzrdblzzrd** [comment]
@TheSparkyGhost With plugin version `1.3.0`, this error also crashed ASF for me, so I updated to pre-release 1.4.1. As of version `1.4.1`, this error simply prevents the plugin from working, but does not crash ASF.

**Comment by TheSparkyGhost** [comment]
@lzrdblzzrd I gotcha.. i've deleted my reply and created a separate ticket for the version I am using! thanks!

**Comment by TheSparkyGhost** [comment]
I noticed Maxisoft has had no activity since the first week of November.. have they moved on to other projects?

**Comment by lzrdblzzrd** [comment]
> I noticed Maxisoft has had no activity since the first week of November.. have they moved on to other projects?

I think he is just busy with his personal life, or he has simply burned out and has no interest in developing the plugin.

In any case, if someone is using Docker, you can run [this program](https://github.com/C4illin/ASFclaim) in it, it works on the same principle and takes free games from the same resource as this plugin.

**Comment by maxisoft** [comment]
Hey all,

Just a heads up that issue #50 with the error on the latest ASF version is now sorted out in the new plugin update (check out PR #65).

Thanks for pointing it out and for the patience. Update to version 1.5.1 and it should be smooth sailing from here.

Cheers,
Maxisoft
